#pragma once

#include "reset_vector.hpp"
#include "variate.hpp"
#include "get_network_total_error.hpp"
#include "print_matrix.hpp"
#include "average.hpp"
#include "colors.hpp"
#include "ramdomly_variate_network_weights.hpp"
#include "reset_matrix.hpp"
#include "in.hpp"
#include "vector_packager.hpp"
#include "Network.hpp"
#include "get_merged_strings.hpp"
#include "read_file.hpp"
#include "dpkg.hpp"
#include "split.hpp"
#include "print_layer_data.hpp"
#include "is_largest.hpp"
#include "matrix_transponser.hpp"
#include "double_packager.hpp"
#include "ask_network_input_from_user.hpp"

#include "repack_network.hpp"

#include "write_file.hpp"
#include "repack.hpp"
#include "layer_runner.hpp"
#include "matrix_randomizer.hpp"
#include "Layer.hpp"
#include "random_bool.hpp"
#include "variate_matrix.hpp"
#include "multiply_scalar_by_vector.hpp"

#include "print_vector.hpp"
#include "absolute_difference.hpp"
#include "get_variation_scope.hpp"

#include "get_vectorized_string.hpp"